//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme2.asd {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestMerchInfoWSResponse", Namespace="http://www.bkmexpress.com.tr")]
    [System.SerializableAttribute()]
    public partial class RequestMerchInfoWSResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosPasswordField;
        
        private bool S3DAuthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MpiUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MpiUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MpiPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XIdField;
        
        private bool S3DFDecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deneme2.asd.Result ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PosUrl {
            get {
                return this.PosUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PosUrlField, value) != true)) {
                    this.PosUrlField = value;
                    this.RaisePropertyChanged("PosUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PosUserId {
            get {
                return this.PosUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PosUserIdField, value) != true)) {
                    this.PosUserIdField = value;
                    this.RaisePropertyChanged("PosUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PosPassword {
            get {
                return this.PosPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PosPasswordField, value) != true)) {
                    this.PosPasswordField = value;
                    this.RaisePropertyChanged("PosPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool S3DAuth {
            get {
                return this.S3DAuthField;
            }
            set {
                if ((this.S3DAuthField.Equals(value) != true)) {
                    this.S3DAuthField = value;
                    this.RaisePropertyChanged("S3DAuth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MpiUrl {
            get {
                return this.MpiUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.MpiUrlField, value) != true)) {
                    this.MpiUrlField = value;
                    this.RaisePropertyChanged("MpiUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MpiUserId {
            get {
                return this.MpiUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MpiUserIdField, value) != true)) {
                    this.MpiUserIdField = value;
                    this.RaisePropertyChanged("MpiUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MpiPassword {
            get {
                return this.MpiPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.MpiPasswordField, value) != true)) {
                    this.MpiPasswordField = value;
                    this.RaisePropertyChanged("MpiPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MD {
            get {
                return this.MDField;
            }
            set {
                if ((object.ReferenceEquals(this.MDField, value) != true)) {
                    this.MDField = value;
                    this.RaisePropertyChanged("MD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string XId {
            get {
                return this.XIdField;
            }
            set {
                if ((object.ReferenceEquals(this.XIdField, value) != true)) {
                    this.XIdField = value;
                    this.RaisePropertyChanged("XId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool S3DFDec {
            get {
                return this.S3DFDecField;
            }
            set {
                if ((this.S3DFDecField.Equals(value) != true)) {
                    this.S3DFDecField = value;
                    this.RaisePropertyChanged("S3DFDec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CustomerIP {
            get {
                return this.CustomerIPField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIPField, value) != true)) {
                    this.CustomerIPField = value;
                    this.RaisePropertyChanged("CustomerIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Extra {
            get {
                return this.ExtraField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraField, value) != true)) {
                    this.ExtraField = value;
                    this.RaisePropertyChanged("Extra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public deneme2.asd.Result Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://www.bkmexpress.com.tr")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int resultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultDetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.resultMsgField, value) != true)) {
                    this.resultMsgField = value;
                    this.RaisePropertyChanged("resultMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resultDet {
            get {
                return this.resultDetField;
            }
            set {
                if ((object.ReferenceEquals(this.resultDetField, value) != true)) {
                    this.resultDetField = value;
                    this.RaisePropertyChanged("resultDet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bkmexpress.com.tr", ConfigurationName="asd.bkm_pos_serviceSoap")]
    public interface bkm_pos_serviceSoap {
        
        // CODEGEN: Generating message contract since element name requestMerchInfoResult from namespace http://www.bkmexpress.com.tr is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bkmexpress.com.tr/requestMerchInfo", ReplyAction="*")]
        deneme2.asd.requestMerchInfoResponse requestMerchInfo(deneme2.asd.requestMerchInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bkmexpress.com.tr/requestMerchInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<deneme2.asd.requestMerchInfoResponse> requestMerchInfoAsync(deneme2.asd.requestMerchInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestMerchInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="requestMerchInfo", Namespace="http://www.bkmexpress.com.tr", Order=0)]
        public deneme2.asd.requestMerchInfoRequestBody Body;
        
        public requestMerchInfoRequest() {
        }
        
        public requestMerchInfoRequest(deneme2.asd.requestMerchInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class requestMerchInfoRequestBody {
        
        public requestMerchInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestMerchInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="requestMerchInfoResponse", Namespace="http://www.bkmexpress.com.tr", Order=0)]
        public deneme2.asd.requestMerchInfoResponseBody Body;
        
        public requestMerchInfoResponse() {
        }
        
        public requestMerchInfoResponse(deneme2.asd.requestMerchInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.bkmexpress.com.tr")]
    public partial class requestMerchInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public deneme2.asd.RequestMerchInfoWSResponse requestMerchInfoResult;
        
        public requestMerchInfoResponseBody() {
        }
        
        public requestMerchInfoResponseBody(deneme2.asd.RequestMerchInfoWSResponse requestMerchInfoResult) {
            this.requestMerchInfoResult = requestMerchInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface bkm_pos_serviceSoapChannel : deneme2.asd.bkm_pos_serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class bkm_pos_serviceSoapClient : System.ServiceModel.ClientBase<deneme2.asd.bkm_pos_serviceSoap>, deneme2.asd.bkm_pos_serviceSoap {
        
        public bkm_pos_serviceSoapClient() {
        }
        
        public bkm_pos_serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public bkm_pos_serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bkm_pos_serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bkm_pos_serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        deneme2.asd.requestMerchInfoResponse deneme2.asd.bkm_pos_serviceSoap.requestMerchInfo(deneme2.asd.requestMerchInfoRequest request) {
            return base.Channel.requestMerchInfo(request);
        }
        
        public deneme2.asd.RequestMerchInfoWSResponse requestMerchInfo() {
            deneme2.asd.requestMerchInfoRequest inValue = new deneme2.asd.requestMerchInfoRequest();
            inValue.Body = new deneme2.asd.requestMerchInfoRequestBody();
            deneme2.asd.requestMerchInfoResponse retVal = ((deneme2.asd.bkm_pos_serviceSoap)(this)).requestMerchInfo(inValue);
            return retVal.Body.requestMerchInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<deneme2.asd.requestMerchInfoResponse> deneme2.asd.bkm_pos_serviceSoap.requestMerchInfoAsync(deneme2.asd.requestMerchInfoRequest request) {
            return base.Channel.requestMerchInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<deneme2.asd.requestMerchInfoResponse> requestMerchInfoAsync() {
            deneme2.asd.requestMerchInfoRequest inValue = new deneme2.asd.requestMerchInfoRequest();
            inValue.Body = new deneme2.asd.requestMerchInfoRequestBody();
            return ((deneme2.asd.bkm_pos_serviceSoap)(this)).requestMerchInfoAsync(inValue);
        }
    }
}
